basicpro/basicapp/urls.py
from django.conf.urls import url
from basicapp import views

app_name='basicapp'

urlpatterns=[
    url(r'^register/$',views.registration,name='registration'),
    url(r'^user_login/$',views.user_login,name='user_login')
]

basicpro/basicpro/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from basicapp import views
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^basicapp/',include('basicapp.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/',views.special,name='special'),
]

basicpro/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
	user=models.OneToOneField(User)

	portfolio_site=models.URLField(blank=True)

	profile_pic=models.ImageField(upload_to='profile_pics',blank=True)

	def __str__(self):
		return self.user.username
		

basicpro/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo

class UserForm(forms.ModelForm):
	password=forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model=User
		fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
	class Meta:
		model=UserProfileInfo
		fields=('portfolio_site','profile_pic')

basicpro/basicapp/views.py
from django.shortcuts import render
from basicapp.forms import UserForm,UserProfileInfoForm
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
	return render(request,'basicapp/index.html')

@login_required
def special(request):
	return HttpResponse("You are login")


@login_required	
def user_logout(request):
	logout(request)
	return HttpResponseRedirect(reverse('index'))

def registration(request):
	registered=False
	if request.method=="POST":
		user_form=UserForm(data=request.POST)
		profile_form=UserProfileInfoForm(data=request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user=user_form.save()
			user.set_password(user.password)
			user.save()

			profile=profile_form.save(commit=False)
			profile.user=user

			if 'profile_pic' in request.FILES:
				profile.profile_pic=request.FILES['profile_pic']
			profile.save()	
			registered=True
		else:
			print(user_form.errors,profile_form.errors)
	else:
		user_form=UserForm()
		profile_form=UserProfileInfoForm()

	return render(request,'basicapp/registration.html',{'user_form':user_form,'profile_form':profile_form,'registered':registered})	

def user_login(request):
	if request.method=='POST':
		username=request.POST.get('username')
		password=request.POST.get('password')

		user=authenticate(username=username,password=password)
		if user:
			if user.is_active:
				login(request,user)
				return HttpResponseRedirect(reverse('index'))
			else:
				return HttpResponse("acoount is not active")
		else:
			print("some one tried to login failed")
			print("username: {} password:{}".format(username,password))
			return HttpResponse("invalid details")
				
	else:
		return render(request,'basicapp/login.html',{})
				
				

			
			

basicpro/templates/basicapp/base.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
	<div class="container">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
		  <a class="navbar-brand" href="#">Navbar</a>
		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
		    <div class="navbar-nav">
		      <a class="nav-item nav-link active" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
		      <a class="nav-item nav-link" href="{% url 'basicapp:registration' %}">Registration</a>
		      <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
		      {% if user.is_authenticated %}
		        <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
		      {%else%}  
		         <a class="nav-item nav-link" href="{% url 'basicapp:user_login' %}">Login</a>
		      {% endif %}   
		      
		    </div>
		  </div>
		</nav>
	</div>
 <div class="container">
 	{% block body_block %}

 	{% endblock %}
 </div>
 	


</body>
</html>

basicpro/templates/basicapp/index.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}
<h1>home</h1>

{% endblock %}

basicpro/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block body_block %}
<h1>Please Login</h1>
<form action="{% url 'basicapp:user_login' %}" method="post">
	{% csrf_token %}
	<label for="username">UserName:</label>
	<input type="text" name="username" placeholder="Enter Ur Text">
	<label for="password">Password:</label>
	<input type="password" name="password">
	
	<input type="submit" name="" value="Login">
	
</form>
{% endblock %}

basicpro/templates/basicapp/registration.html
<!DOCTYPE html>
{% extends 'basicapp/base.html' %}
{% block body_block %}
{% if registered %}
<h1>Thank u for registrations</h1>
{% else %}
<h1>Register here</h1>
<form enctype="multipart/from-data" method="post">
	{% csrf_token %}
	{{user_form.as_p}}
	{{profile_form.as_p}}
	<input type="submit" value="register">
	
	
</form>


{% endif %}

{% endblock %}